Repository cjwilburn/dank-memes, pull requests merged in 2018-10, with the labels that each got.

#10 yeet
  README.md
Labels: Hacktoberfest

#13 added reddit memes
  reddit.js
Labels: Hacktoberfest

#17 added docs folder and sample files
  docs/commands.md
  docs/contributing.md
Labels: Hacktoberfest, good first issue

#11 generate a random meme from imgflip
  index.js
  package.json
Labels: Hacktoberfest

#12 Updated readme
  README.md
Labels: Hacktoberfest

#22 adding templates and moving contributing markdown file. fixes #19. cl…
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Hacktoberfest

#23 Add "meme roulette"
  roulette.js
  yarn.lock
Labels: Hacktoberfest, enhancement

#26 Fix issue where node process hangs after successful dank meme generation.
  index.js
  reddit.js
  roulette.js
Labels: Hacktoberfest, bug

#32 Meme generation CLI
  make-meme.js
Labels: Hacktoberfest

#33 Ron Swanson meme-generator
  ron-swanson.js
Labels: Hacktoberfest

#36 Add "Dankest Dungeon" memes
  dankest-dungeon.js
Labels: Hacktoberfest

#37 Remove max memes as it broke deep delving
  dankest-dungeon.js
Labels: Hacktoberfest
